begin;

-- Thông tin tài xế được phân công trên từng booking.
alter table public.bookings
  add column if not exists driver_id uuid references public.profiles(id) on delete set null,
  add column if not exists driver_name text,
  add column if not exists route_distance_km numeric,
  add column if not exists route_duration_min integer,
  add column if not exists route_geometry jsonb,
  add column if not exists route_milestones jsonb,
  add column if not exists origin_text text,
  add column if not exists destination_text text,
  add column if not exists origin_lat numeric,
  add column if not exists origin_lng numeric,
  add column if not exists destination_lat numeric,
  add column if not exists destination_lng numeric,
  add column if not exists current_stage text,
  add column if not exists current_progress_percent numeric not null default 0,
  add column if not exists current_location text,
  add column if not exists distance_traveled_km numeric,
  add column if not exists distance_remaining_km numeric,
  add column if not exists tracking_note text,
  add column if not exists last_tracking_at timestamptz,
  add column if not exists delivery_recipient_name text,
  add column if not exists delivery_recipient_phone text,
  add column if not exists delivered_at timestamptz,
  add column if not exists delivery_condition text,
  add column if not exists delivery_note text,
  add column if not exists delivery_proof_path text,
  add column if not exists completed_at timestamptz;

-- Phiên bản cũ chỉ cho phép hai tên tuyến cố định.
-- Phiên bản mới chấp nhận mọi tuyến động miễn tên tuyến không rỗng.
alter table public.bookings
  drop constraint if exists bookings_route_check;

alter table public.bookings
  add constraint bookings_route_check
  check (route is not null and char_length(btrim(route)) > 0);

-- Mở rộng vòng đời booking với trạng thái giao hàng hoàn tất.
alter table public.bookings
  drop constraint if exists bookings_status_check;

alter table public.bookings
  add constraint bookings_status_check
  check (status in ('pending', 'matched', 'confirmed', 'cancelled', 'delivered'));

alter table public.bookings
  drop constraint if exists bookings_delivery_condition_check;

alter table public.bookings
  add constraint bookings_delivery_condition_check
  check (
    delivery_condition is null
    or delivery_condition in ('good', 'needs_review', 'damaged')
  );

alter table public.bookings
  drop constraint if exists bookings_delivery_completion_check;

alter table public.bookings
  add constraint bookings_delivery_completion_check
  check (
    status <> 'delivered'
    or (
      current_progress_percent = 100
      and delivery_recipient_name is not null
      and delivered_at is not null
      and delivery_condition is not null
      and delivery_proof_path is not null
      and completed_at is not null
    )
  );

create index if not exists bookings_driver_id_idx
on public.bookings (driver_id);

-- Cho phép đơn vị vận tải chọn các tài xế đã đăng ký.
drop policy if exists "Don vi van tai xem ho so tai xe"
on public.profiles;

create policy "Don vi van tai xem ho so tai xe"
on public.profiles
for select
to authenticated
using (
  auth.uid() = id
  or (role = 'driver' and account_status = 'active')
);

-- Tài xế chỉ đọc booking của mình hoặc booking đã được giao cho mình.
drop policy if exists "Tai xe xem booking duoc giao"
on public.bookings;

create policy "Tai xe xem booking duoc giao"
on public.bookings
for select
to authenticated
using (
  auth.uid() = user_id
  or auth.uid() = driver_id
);

-- Bảo đảm đơn vị vận tải có thể xem booking đang mở và booking đã nhận.
drop policy if exists "Don vi van tai xem booking can tiep nhan"
on public.bookings;

create policy "Don vi van tai xem booking can tiep nhan"
on public.bookings
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'carrier'
      and profiles.account_status = 'active'
  )
  and (
    bookings.status = 'pending'
    or bookings.carrier_id = auth.uid()
  )
);

-- Chỉ đơn vị vận tải đang hoạt động được nhận booking đang chờ,
-- rồi xác nhận chính booking do đơn vị đó đã nhận.
drop policy if exists "Don vi van tai cap nhat booking da nhan"
on public.bookings;

create policy "Don vi van tai cap nhat booking da nhan"
on public.bookings
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'carrier'
      and profiles.account_status = 'active'
  )
  and (
    bookings.status = 'pending'
    or bookings.carrier_id = auth.uid()
  )
)
with check (
  bookings.carrier_id = auth.uid()
  and bookings.status in ('matched', 'confirmed')
);

grant select, update on table public.bookings to authenticated;

-- Lịch sử cập nhật thủ công của tài xế.
create table if not exists public.tracking_events (
  id bigint generated by default as identity primary key,
  booking_id text not null,
  driver_id uuid not null references public.profiles(id) on delete cascade,
  stage text not null,
  milestone_percent numeric,
  location_text text not null,
  distance_traveled_km numeric,
  distance_remaining_km numeric,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists tracking_events_booking_id_idx
on public.tracking_events (booking_id);

create index if not exists tracking_events_driver_id_idx
on public.tracking_events (driver_id);

alter table public.tracking_events enable row level security;

alter table public.tracking_events
  add column if not exists milestone_percent numeric;

drop policy if exists "Nguoi dung xem lich su tracking"
on public.tracking_events;

create policy "Nguoi dung xem lich su tracking"
on public.tracking_events
for select
to authenticated
using (
  auth.uid() = driver_id
  or exists (
    select 1
    from public.bookings
    where bookings.id::text = tracking_events.booking_id
      and (bookings.user_id = auth.uid() or bookings.carrier_id = auth.uid())
  )
);

drop policy if exists "Tai xe them lich su tracking"
on public.tracking_events;

create policy "Tai xe them lich su tracking"
on public.tracking_events
for insert
to authenticated
with check (
  auth.uid() = driver_id
  and exists (
    select 1
    from public.bookings
    where bookings.id::text = tracking_events.booking_id
      and bookings.driver_id = auth.uid()
  )
);

grant select, insert on table public.tracking_events to authenticated;
grant usage, select on sequence public.tracking_events_id_seq to authenticated;

drop policy if exists "Tai xe cap nhat booking duoc giao"
on public.bookings;

create policy "Tai xe cap nhat booking duoc giao"
on public.bookings
for update
to authenticated
using (auth.uid() = driver_id)
with check (auth.uid() = driver_id);

-- Lưu quyết định từ chối riêng của từng đơn vị vận tải.
-- booking_id dùng kiểu text để tương thích với cả bảng bookings dùng UUID
-- lẫn bảng dùng khóa số trong các phiên bản dự án cũ.
create table if not exists public.booking_responses (
  id bigint generated by default as identity primary key,
  booking_id text not null,
  carrier_id uuid not null references public.profiles(id) on delete cascade,
  decision text not null default 'rejected'
    check (decision in ('rejected')),
  created_at timestamptz not null default now(),
  unique (booking_id, carrier_id)
);

create index if not exists booking_responses_carrier_id_idx
on public.booking_responses (carrier_id);

create index if not exists booking_responses_booking_id_idx
on public.booking_responses (booking_id);

alter table public.booking_responses enable row level security;

drop policy if exists "Don vi van tai xem phan hoi cua minh"
on public.booking_responses;

create policy "Don vi van tai xem phan hoi cua minh"
on public.booking_responses
for select
to authenticated
using (auth.uid() = carrier_id);

drop policy if exists "Don vi van tai tu choi booking"
on public.booking_responses;

create policy "Don vi van tai tu choi booking"
on public.booking_responses
for insert
to authenticated
with check (
  auth.uid() = carrier_id
  and decision = 'rejected'
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'carrier'
      and profiles.account_status = 'active'
  )
  and exists (
    select 1
    from public.bookings
    where bookings.id::text = booking_id
      and bookings.status = 'pending'
  )
);

grant select, insert on table public.booking_responses to authenticated;
grant usage, select on sequence public.booking_responses_id_seq to authenticated;

-- Bucket riêng tư lưu ảnh biên bản/bằng chứng giao hàng (tối đa 5 MB).
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'delivery-proofs',
  'delivery-proofs',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Tai xe tai anh giao hang"
on storage.objects;

create policy "Tai xe tai anh giao hang"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'delivery-proofs'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Nguoi lien quan xem anh giao hang"
on storage.objects;

create policy "Nguoi lien quan xem anh giao hang"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'delivery-proofs'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or exists (
      select 1
      from public.bookings
      where bookings.delivery_proof_path = storage.objects.name
        and (
          bookings.user_id = auth.uid()
          or bookings.carrier_id = auth.uid()
          or bookings.driver_id = auth.uid()
        )
    )
  )
);

drop policy if exists "Tai xe xoa anh giao hang cua minh"
on storage.objects;

create policy "Tai xe xoa anh giao hang cua minh"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'delivery-proofs'
  and (storage.foldername(name))[1] = auth.uid()::text
);

commit;
