begin;

-- Bảo đảm đơn vị vận tải có thể xem booking đang mở và booking đã nhận.
drop policy if exists "Don vi van tai xem booking can tiep nhan"
on public.bookings;

create policy "Don vi van tai xem booking can tiep nhan"
on public.bookings
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'carrier'
      and profiles.account_status = 'active'
  )
  and (
    bookings.status = 'pending'
    or bookings.carrier_id = auth.uid()
  )
);

-- Chỉ đơn vị vận tải đang hoạt động được nhận booking đang chờ,
-- rồi xác nhận chính booking do đơn vị đó đã nhận.
drop policy if exists "Don vi van tai cap nhat booking da nhan"
on public.bookings;

create policy "Don vi van tai cap nhat booking da nhan"
on public.bookings
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'carrier'
      and profiles.account_status = 'active'
  )
  and (
    bookings.status = 'pending'
    or bookings.carrier_id = auth.uid()
  )
)
with check (
  bookings.carrier_id = auth.uid()
  and bookings.status in ('matched', 'confirmed')
);

grant select, update on table public.bookings to authenticated;

-- Lưu quyết định từ chối riêng của từng đơn vị vận tải.
-- booking_id dùng kiểu text để tương thích với cả bảng bookings dùng UUID
-- lẫn bảng dùng khóa số trong các phiên bản dự án cũ.
create table if not exists public.booking_responses (
  id bigint generated by default as identity primary key,
  booking_id text not null,
  carrier_id uuid not null references public.profiles(id) on delete cascade,
  decision text not null default 'rejected'
    check (decision in ('rejected')),
  created_at timestamptz not null default now(),
  unique (booking_id, carrier_id)
);

create index if not exists booking_responses_carrier_id_idx
on public.booking_responses (carrier_id);

create index if not exists booking_responses_booking_id_idx
on public.booking_responses (booking_id);

alter table public.booking_responses enable row level security;

drop policy if exists "Don vi van tai xem phan hoi cua minh"
on public.booking_responses;

create policy "Don vi van tai xem phan hoi cua minh"
on public.booking_responses
for select
to authenticated
using (auth.uid() = carrier_id);

drop policy if exists "Don vi van tai tu choi booking"
on public.booking_responses;

create policy "Don vi van tai tu choi booking"
on public.booking_responses
for insert
to authenticated
with check (
  auth.uid() = carrier_id
  and decision = 'rejected'
  and exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'carrier'
      and profiles.account_status = 'active'
  )
  and exists (
    select 1
    from public.bookings
    where bookings.id::text = booking_id
      and bookings.status = 'pending'
  )
);

grant select, insert on table public.booking_responses to authenticated;
grant usage, select on sequence public.booking_responses_id_seq to authenticated;

commit;
